### PR TITLE
Fixed reference to the perspective method

### LINKED ISSUE #5: The plugin doesn't work with the latest Highcharts version
The plugin doesn't work from the Highcharts version higher than 10.2.0.

Error log:
error

### PR DESCRIPTION
**Pull request by ddragula**
Resolved #5, fixed wrong reference to the perspective method.

### CODE REVIEW

File: js/projections.js [hunk 1]
```diff
@@ -20,6 +20,7 @@
 		factory(Highcharts);
 	}
 }(function (H) {
+	H.perspective = H._modules['Core/Math3D.js'].perspective;
```
Comment (raf18seb) [inline js/projections.js]: This method used to be on the Highcharts object (H.) then it was moved to a new module. Now there's no point to store it on the Highcharts object again. Instead, a simple local variable would do the job, like:
```js
const perspective = ...;
```

**Review by raf18seb — CHANGES_REQUESTED** [review]

**Review by raf18seb — CHANGES_REQUESTED** [review]
Wrong button, it should be "Request changes"

File: js/projections.js [hunk 2]
```diff
@@ -20,9 +20,7 @@
 		factory(Highcharts);
 	}
 }(function (H) {
-
-	var PlaneProjection,
-		LineProjection,
+	const perspective = H._modules['Core/Math3D.js'].perspective,
```
Comment (raf18seb) [inline js/projections.js]: One more thing, sorry! I suggested `const`, but we're still using ES5 here so `var` would be better

**Review by raf18seb — CHANGES_REQUESTED** [review]

**Review by raf18seb — APPROVED** [review]
Thanks!
